version: '3'

services:
  db:
    image: postgres:latest
    container_name: "postgres"
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - database_data:/var/lib/postgresql/data

  compendium:
    image: 47deg/compendium:latest
    expose:
      - 8080
    ports:
      - 8080:8080
    links:
      - db
    depends_on:
      - db
    environment:
      COMPENDIUM_METADATA_STORAGE_JDBC_URL: 'jdbc:postgresql://db:5432/postgres'
      COMPENDIUM_METADATA_STORAGE_USERNAME: 'postgres'
      COMPENDIUM_METADATA_STORAGE_PASSWORD: 'postgres'


volumes:
  database_data:
    driver: local
