package compendiumtest

import cats.effect.{ExitCode, IO, IOApp}
import io.chrisdavenport.log4cats.SelfAwareStructuredLogger
import io.chrisdavenport.log4cats.slf4j.Slf4jLogger

object Main extends IOApp {

  implicit val logger: SelfAwareStructuredLogger[IO] =
    Slf4jLogger.getLogger

  override def run(args: List[String]): IO[ExitCode] = {

    for {
      _ <- logger.info(
        "Start reading the csv files. Data automatically generated by Mockaroo."
      )

      _ <- logger.info("Bye!")
    } yield ExitCode.Success
  }
}
